### ISSUE TITLE
window.gapi is undefined when using React-google-drive-picker more than once in same page

### ISSUE THREAD

**Issue by damoclark** [Jose-cd/React-google-drive-picker#2]
When attempting to load more than one picker into the same page, get the error `window.gapi is undefined`.  It appears that there is a race condition in `useDrivePicker()` when it is called multiple times during a render.  

In `useInjectScript()` function, the url is added to the `cachedScripts` array before the callback `onScriptLoad()` is called when the script tag is added to the DOM.  So the next call to `useDrivePicker()` sees that the URL is cached in `cachedScripts` but not yet loaded into the DOM, thus causing the above error.

Perhaps move the line:

```javascript
	cachedScripts.push(url);
```

into the `onScriptLoad` method.

Although this risks adding the script multiple times though.  The `loaded` property of the state, might need to hold 3 different state levels (rather than just two with a boolean).  loaded: 'no', loaded: 'loading', loaded: 'yes'.  

I'll see if I can prepare a simple PR.

**Comment by damoclark** [comment]
[Messy and untested](https://github.com/damoclark/React-google-drive-picker/tree/race_fix).  Sorry, just ran out of time, but in hopes might help.

**Comment by Jose-cd** [comment]
> [Messy and untested](https://github.com/damoclark/React-google-drive-picker/tree/race_fix). Sorry, just ran out of time, but in hopes might help.

Thank you, it is working now, we are injecting the script multiple times though, I couldn't find a way to fix that.

I tried:
1. If the script already exists in the DOM setState({loaded: true}), this doesnt work because it is not waiting for the script to load before updating the state.
2. If the script already exists in the DOM set an event listener, this doesnt work because the first event listener cancels the second event listener and ends up having only 1 instance of the hook ready loaded.
